[tool.poetry]
name = "ml-model-service"
version = "0.1.0"
description = "API for training and using ML models"
authors = ["shevchenkokk <kirill_07_02@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.120.3"
uvicorn = "^0.38.0"
scikit-learn = "^1.7.2"
pandas = "^2.3.3"
lightgbm = "^4.6.0"
streamlit = "^1.51.0"
grpcio = "^1.76.0"
grpcio-tools = "^1.76.0"
ruff = "^0.14.3"
python-jose = {extras = ["cryptography"], version = "^3.5.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-dotenv = "^1.2.1"
python-multipart = "^0.0.20"
bcrypt = "4.3.0"
pydantic-settings = "^2.12.0"
boto3 = "^1.35.82"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
